version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./srv/postgres:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/database/payouts_init.sql:/docker-entrypoint-initdb.d/payouts_init.sql

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "0.0.0.0:5432:5432"
    restart: always
  casino-backend:
    image: eclipse-temurin:latest
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      - "db"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
  # casino-frontend:
  #   build:
  #     context: .
  #     dockerfile: frontend/frontend.Dockerfile
  #   restart: unless-stopped
  #   expose:
  #     - "12345"
  #     - "80"
  #   ports:
  #     - "0.0.0.0:80:80"
  #     - "0.0.0.0:12345:12345"
  #   depends_on:
  #     - "casino-backend"
